"""empty message

Revision ID: 35661a53f602
Revises: 377bde363b79
Create Date: 2023-11-01 23:52:34.663078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35661a53f602'
down_revision = '377bde363b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('eye_color',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('eye_color',
               existing_type=sa.String(length=250),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
